server:
  port: 8080
spring:
  application:
    name: greeting
  config:
    import: optional:config-server:http://localhost:8888/
  cloud:
    config:
      profile: prod
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
greeting-service:
  greeting: "Olá"
  default-value: "Mundo"

